all:
	python drawmaps.py 250 2 1 1 > ./model-1x1/model1x1-h250-o2.txt
	python drawmaps.py 200 2 1 1 > ./model-1x1/model1x1-h200-o2.txt
	python drawmaps.py 150 2 1 1 > ./model-1x1/model1x1-h150-o2.txt
	python drawmaps.py 100 2 1 1 > ./model-1x1/model1x1-h100-o2.txt
	python drawmaps.py 70  2 1 1 > ./model-1x1/model1x1-h70-o2.txt
	python drawmaps.py 60  2 1 1 > ./model-1x1/model1x1-h60-o2.txt
	python drawmaps.py 50  2 1 1 > ./model-1x1/model1x1-h50-o2.txt
	python drawmaps.py 40  2 1 1 > ./model-1x1/model1x1-h40-o2.txt
	python drawmaps.py 30  2 1 1 > ./model-1x1/model1x1-h30-o2.txt
	python drawmaps.py 30  5 1 1 > ./model-1x1/model1x1-h30-o5.txt
	python drawmaps.py 30  6 1 1 > ./model-1x1/model1x1-h30-o6.txt
	python drawmaps.py 30  7 1 1 > ./model-1x1/model1x1-h30-o7.txt
	python drawmaps.py 30  8 1 1 > ./model-1x1/model1x1-h30-o8.txt
	python drawmaps.py 30  9 1 1 > ./model-1x1/model1x1-h30-o9.txt
	python drawmaps.py 20  2 1 1 > ./model-1x1/model1x1-h20-o2.txt
	python drawmaps.py 10  2 1 1 > ./model-1x1/model1x1-h10-o2.txt
	python drawmaps.py 5   2 1 1 > ./model-1x1/model1x1-h5-o2.txt
	python drawmaps.py 1   2 1 1 > ./model-1x1/model1x1-h1-o2.txt
	python drawmaps.py 30  2 3 3 > ./model-3x3/model3x3-h30-o2.txt
	python drawmaps.py 30  3 3 3 > ./model-3x3/model3x3-h30-o3.txt
	python drawmaps.py 10 17 1 1 > ./model-1x1/model1x1-h10-o17.txt
	python drawmaps.py 10 18 1 1 > ./model-1x1/model1x1-h10-o18.txt
	python drawmaps.py 10 19 1 1 > ./model-1x1/model1x1-h10-o19.txt
	python drawmaps.py 10  2 3 3 > ./model-3x3/model3x3-h10-o2.txt
	python drawmaps.py 10  3 3 3 > ./model-3x3/model3x3-h10-o3.txt
	python drawmaps.py 10  4 3 3 > ./model-3x3/model3x3-h10-o4.txt
	python drawmaps.py 10  5 3 3 > ./model-3x3/model3x3-h10-o5.txt
	python drawmaps.py 10  6 3 3 > ./model-3x3/model3x3-h10-o6.txt
	python drawmaps.py 10  7 3 3 > ./model-3x3/model3x3-h10-o7.txt
	python drawmaps.py 10  8 3 3 > ./model-3x3/model3x3-h10-o8.txt
	python drawmaps.py 10  9 3 3 > ./model-3x3/model3x3-h10-o9.txt
	python drawmaps.py 10  2 7 7 > ./model-7x7/model7x7-h10-o2.txt
	python drawmaps.py 10  3 7 7 > ./model-7x7/model7x7-h10-o3.txt
	python drawmaps.py 10  4 7 7 > ./model-7x7/model7x7-h10-o4.txt

nosave:
	python drawmaps.py 250 2 1 1 
	python drawmaps.py 200 2 1 1 
	python drawmaps.py 150 2 1 1 
	python drawmaps.py 100 2 1 1 
	python drawmaps.py 70  2 1 1 
	python drawmaps.py 60  2 1 1 
	python drawmaps.py 50  2 1 1 
	python drawmaps.py 40  2 1 1 
	python drawmaps.py 30  2 1 1 
	python drawmaps.py 30  5 1 1 
	python drawmaps.py 30  6 1 1 
	python drawmaps.py 30  7 1 1 
	python drawmaps.py 30  8 1 1 
	python drawmaps.py 30  9 1 1 
	python drawmaps.py 20  2 1 1 
	python drawmaps.py 10  2 1 1 
	python drawmaps.py 5   2 1 1 
	python drawmaps.py 1   2 1 1 
	python drawmaps.py 30  2 3 3 
	python drawmaps.py 30  3 3 3 
	python drawmaps.py 10 17 1 1
	python drawmaps.py 10 18 1 1
	python drawmaps.py 10 19 1 1
	python drawmaps.py 10  2 3 3 
	python drawmaps.py 10  3 3 3 
	python drawmaps.py 10  4 3 3 
	python drawmaps.py 10  5 3 3 
	python drawmaps.py 10  6 3 3 
	python drawmaps.py 10  7 3 3 
	python drawmaps.py 10  8 3 3 
	python drawmaps.py 10  9 3 3 
	python drawmaps.py 10  2 7 7 
	python drawmaps.py 10  3 7 7 
	python drawmaps.py 10  4 7 7 
